name: battery_plus
publish_to: none
description: Flutter plugin for accessing information about the battery state(full, charging, discharging).
version: 4.0.2
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/battery_plus/battery_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/battery_plus

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.battery
        pluginClass: BatteryPlusPlugin
      ios:
        pluginClass: FLTBatteryPlusPlugin
      linux:
        dartPluginClass: BatteryPlusLinuxPlugin
      macos:
        pluginClass: BatteryPlusMacosPlugin
      web:
        pluginClass: BatteryPlusWebPlugin
        fileName: src/battery_plus_web.dart
      windows:
        pluginClass: BatteryPlusWindowsPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  battery_plus_platform_interface: 
    git: https://github.com/kumsumit/battery_plus_platform_interface.git 
  meta: ^1.9.1
  upower:
    git: https://github.com/kumsumit/upower.dart.git 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  async: ^2.10.0
  flutter_lints:
    git: https://github.com/kumsumit/flutter_lints.git
  mockito: ^5.4.2
  plugin_platform_interface: 
    git: https://github.com/kumsumit/plugin_platform_interface.git

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"
